config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvpbis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container py-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Restaurant</h1>
    <div class="col-md-8 my-4">
      <% @restaurants.each do |restaurant| %>
        <div class="row">
          <%= link_to restaurant[:name], restaurant_path(restaurant), class:"fs-5" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 fs-4">
      <%= link_to "Create new restaurant", new_restaurant_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">New restaurant</h1>
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category %>
      <%= f.submit %>
    <% end %>
    <%# <%= link_to "Edit the restaurant", edit_restaurant %>
    <%# <button class="btn btn-primary btn-lg" type="button">Example button</button> %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <%= link_to "🔙", restaurants_path, class:'link-icon' %>
  <div class="container-fluid py-5">
    <div class="row">
      <div class="col-md-8">
        <h1 class="display-5 fw-bold"><%= @restaurant[:name] %></h1>
        <p class=""><%=  @restaurant[:address] %></p>
        <p class=""><%=  @restaurant[:phone_number] %></p>
        <p>Reviews :</p>
        <% @restaurant.reviews.each do |review|%>
        <p> <%= review.rating %></p>
        <p> <%= review.content %></p>
        <% end %>
        <%= link_to "Write new review", new_restaurant_review_path(@restaurant), class: 'm-3' %>
      </div>
      <div class="col-md-4">
        <div class="d-flex flex-column align-items-center justify-content-center">
          <%# <%= link_to "Edit the restaurant", edit_restaurant_path, class: 'm-3' %>
          <%= link_to "🗑",
                      restaurant_path,
                      method: :delete,
                      data: { confirm: "Are you sure?" },
                      class:'link-icon' %>
        </div>
      </div>
  </div>

    <%# <button class="btn btn-primary btn-lg" type="button">Example button</button> %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">New Review of " <%= @restaurant.name %> "</h1>
    <%= simple_form_for([@restaurant, @review]) do |f| %>
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit %>
    <% end %>
    <%# <%= link_to "Edit the restaurant", edit_restaurant %>
    <%# <button class="btn btn-primary btn-lg" type="button">Example button</button> %>
  </div>
</div>